APT::FTPArchive::Release::Origin "Porthole";
APT::FTPArchive::Release::Label "Porthole";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Porthole APT repository (Linux, GTK4)";
